### PR TITLE
First PR

### PR DESCRIPTION
**Pull request by zamentur**
This app need a specific dev in the core: https://github.com/YunoHost/yunohost/pull/1706

Currently the auto genration of properties works, but the config panel is broken (even with the core patch).

### CODE REVIEW

**Comment by zamentur** [comment]
!testme

**Comment by zamentur** [comment]
!testme

**Comment by zamentur** [comment]
!testme

**Comment by zamentur** [comment]
!testme

**Comment by zamentur** [comment]
!testme

**Comment by alexAubin** [comment]
!testme

**Comment by alexAubin** [comment]
@zamentur : bumpitybump, sounds like it could ~easily be fixed and integrated in the catalog

**Comment by lapineige** [comment]
```
[main]
name.en = "Organization"
name.fr = "Organisation"
bind = ":{{ install_dir }}/public/organization.properties"

services = []

## (optional) This help properties is a short help displayed on the same line
## than the panel title but not displayed in the tab.
# help = ""
    
    [main.organization]
    name = ""
    # help = ""
    optional = true
```

It doesn't like the 2 "name" defined here :thinking:

**Comment by alexAubin** [comment]
!testme

**Comment by zamentur** [comment]
!testme

**Comment by zamentur** [comment]
!testme

**Comment by zamentur** [comment]
!testme

**Pull request merged**
